const stenoOrderAndEnglishKeys = [
  ["#", "1"],
  ["1", "2"],
  ["S", "3"],
  ["T", "4"],
  ["2", "5"],
  ["K", "6"],
  ["3", "7"],
  ["P", "8"],
  ["W", "9"],
  ["4", "0"],
  ["H", "a"],
  ["R", "b"],
  ["5", "c"],
  ["A", "d"],
  ["0", "e"],
  ["O", "f"],
  ["*", "g"],
  ["E", "h"],
  ["U", "i"],
  ["-", "j"], // right-hand index
  ["6", "k"],
  ["F", "l"],
  ["R", "m"],
  ["7", "n"],
  ["P", "o"],
  ["B", "p"],
  ["8", "q"],
  ["L", "r"],
  ["G", "s"],
  ["9", "t"],
  ["T", "u"],
  ["S", "v"],
  ["D", "w"],
  ["Z", "x"],
];

export const rightHandIndex = 19;

export default stenoOrderAndEnglishKeys;
